name: Build OpenWrt

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Build Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc wget unzip python python3

    - name: Update Feeds
      run: ./scripts/feeds update -a

    - name: Install Feeds
      run: ./scripts/feeds install -a

    - name: Config OpenWrt
      run: |
        make menuconfig

    - name: Build OpenWrt
      run: |
        make defconfig
        make -j$(nproc) download
        make -j$(nproc) V=s
